### GET MED NORMAL
GET http://localhost:1010/doctor

### GET MED PAGEABLE
GET http://localhost:1010/doctor?size=1&page=1

### GET MED PAGEABLE SORT DECRESCENT
GET http://localhost:1010/doctor?sort=name,desc

### GET MED WITH ATIVO TRUE [logical delete]
GET http://localhost:1010/doctor/status

### GET MED WITH ID
GET http://localhost:1010/doctor/50

### POST MED
POST http://localhost:1010/doctor/search
Accept: application/json
Content-Type: application/json

{
  "name": "Fernando Carrilho",
  "email": "fernando.carrilho@gmail.com",
  "crm": "457315",
  "telephone": "(62) 9 9563-1247",
  "specialty": "GINECOLOGIA",
  "address": {
    "place": "Rua a",
    "neighborhood": "Setor Cristina II Expansão",
    "cep": "75389328",
    "city": "Trindade",
    "uf": "GO",
    "number": "4",
    "complement": "casa"
  }
}


### PUT MED
PUT http://localhost:1010/doctor
Accept: application/json
Content-Type: application/json

{
  "id": "4",
  "name": "Bruno Lucas"
}

### DELETE MED
DELETE http://localhost:1010/doctor/1

### LOGICAL DELETE MED
DELETE http://localhost:1010/doctor/logical/4